// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: currency/currency.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *Currency) Reset() {
	*x = Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currency_currency_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CurrencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Ccy       string `protobuf:"bytes,3,opt,name=ccy,proto3" json:"ccy,omitempty"`
	CcyNm_RU  string `protobuf:"bytes,4,opt,name=ccyNm_RU,json=ccyNmRU,proto3" json:"ccyNm_RU,omitempty"`
	CcyNm_UZ  string `protobuf:"bytes,5,opt,name=ccyNm_UZ,json=ccyNmUZ,proto3" json:"ccyNm_UZ,omitempty"`
	CcyNm_UZC string `protobuf:"bytes,6,opt,name=ccyNm_UZC,json=ccyNmUZC,proto3" json:"ccyNm_UZC,omitempty"`
	CcyNm_EN  string `protobuf:"bytes,7,opt,name=ccyNm_EN,json=ccyNmEN,proto3" json:"ccyNm_EN,omitempty"`
	Nominal   string `protobuf:"bytes,8,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Rate      string `protobuf:"bytes,9,opt,name=rate,proto3" json:"rate,omitempty"`
	Diff      string `protobuf:"bytes,10,opt,name=diff,proto3" json:"diff,omitempty"`
	Date      string `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *CurrencyResponse) Reset() {
	*x = CurrencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currency_currency_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyResponse) ProtoMessage() {}

func (x *CurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyResponse.ProtoReflect.Descriptor instead.
func (*CurrencyResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CurrencyResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CurrencyResponse) GetCcy() string {
	if x != nil {
		return x.Ccy
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_RU() string {
	if x != nil {
		return x.CcyNm_RU
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_UZ() string {
	if x != nil {
		return x.CcyNm_UZ
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_UZC() string {
	if x != nil {
		return x.CcyNm_UZC
	}
	return ""
}

func (x *CurrencyResponse) GetCcyNm_EN() string {
	if x != nil {
		return x.CcyNm_EN
	}
	return ""
}

func (x *CurrencyResponse) GetNominal() string {
	if x != nil {
		return x.Nominal
	}
	return ""
}

func (x *CurrencyResponse) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *CurrencyResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *CurrencyResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetAllCurrencyRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count      int32               `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Currencies []*CurrencyResponse `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
}

func (x *GetAllCurrencyRespone) Reset() {
	*x = GetAllCurrencyRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currency_currency_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCurrencyRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCurrencyRespone) ProtoMessage() {}

func (x *GetAllCurrencyRespone) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCurrencyRespone.ProtoReflect.Descriptor instead.
func (*GetAllCurrencyRespone) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllCurrencyRespone) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetAllCurrencyRespone) GetCurrencies() []*CurrencyResponse {
	if x != nil {
		return x.Currencies
	}
	return nil
}

var File_currency_currency_proto protoreflect.FileDescriptor

var file_currency_currency_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x22, 0x26, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x8c, 0x02, 0x0a, 0x10,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x63, 0x63, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x63, 0x79, 0x4e, 0x6d, 0x5f,
	0x52, 0x55, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x63, 0x79, 0x4e, 0x6d, 0x52,
	0x55, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x63, 0x79, 0x4e, 0x6d, 0x5f, 0x55, 0x5a, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x63, 0x79, 0x4e, 0x6d, 0x55, 0x5a, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x63, 0x79, 0x4e, 0x6d, 0x5f, 0x55, 0x5a, 0x43, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x63, 0x79, 0x4e, 0x6d, 0x55, 0x5a, 0x43, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x63, 0x79,
	0x4e, 0x6d, 0x5f, 0x45, 0x4e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x63, 0x79,
	0x4e, 0x6d, 0x45, 0x4e, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x66, 0x66, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x69, 0x66, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x69, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x69, 0x65, 0x73, 0x32, 0x57, 0x0a, 0x0f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x2e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x1a, 0x1f, 0x2e, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x42, 0x0e,
	0x5a, 0x0c, 0x61, 0x70, 0x70, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_currency_currency_proto_rawDescOnce sync.Once
	file_currency_currency_proto_rawDescData = file_currency_currency_proto_rawDesc
)

func file_currency_currency_proto_rawDescGZIP() []byte {
	file_currency_currency_proto_rawDescOnce.Do(func() {
		file_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(file_currency_currency_proto_rawDescData)
	})
	return file_currency_currency_proto_rawDescData
}

var file_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_currency_currency_proto_goTypes = []interface{}{
	(*Currency)(nil),              // 0: currency.Currency
	(*CurrencyResponse)(nil),      // 1: currency.CurrencyResponse
	(*GetAllCurrencyRespone)(nil), // 2: currency.GetAllCurrencyRespone
}
var file_currency_currency_proto_depIdxs = []int32{
	1, // 0: currency.GetAllCurrencyRespone.currencies:type_name -> currency.CurrencyResponse
	0, // 1: currency.CurrencyService.GetCurrency:input_type -> currency.Currency
	2, // 2: currency.CurrencyService.GetCurrency:output_type -> currency.GetAllCurrencyRespone
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_currency_currency_proto_init() }
func file_currency_currency_proto_init() {
	if File_currency_currency_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_currency_currency_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_currency_currency_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_currency_currency_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCurrencyRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_currency_currency_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_currency_proto_goTypes,
		DependencyIndexes: file_currency_currency_proto_depIdxs,
		MessageInfos:      file_currency_currency_proto_msgTypes,
	}.Build()
	File_currency_currency_proto = out.File
	file_currency_currency_proto_rawDesc = nil
	file_currency_currency_proto_goTypes = nil
	file_currency_currency_proto_depIdxs = nil
}
